#!/bin/env ruby

path = File.join(File.dirname(__FILE__), "lib", "gogyou", "primitives.rb")

# type name, byte bytesize, alignment bytesize, store method, load method
records = <<EOS
size_t TypeSpec::SIZEOF_SIZE_T TypeSpec::SIZEOF_SIZE_T store_sizet load_sizet
ssize_t TypeSpec::SIZEOF_SIZE_T TypeSpec::SIZEOF_SIZE_T store_sizet load_ssizet
intptr_t TypeSpec::SIZEOF_SIZE_T TypeSpec::SIZEOF_SIZE_T store_sizet load_ssizet
uintptr_t TypeSpec::SIZEOF_SIZE_T TypeSpec::SIZEOF_SIZE_T store_sizet load_sizet
int8_t    1 1 store8    loadi8
uint8_t   1 1 store8    loadu8
int16_t   2 2 store16   loadi16
uint16_t  2 2 store16   loadu16
int32_t   4 4 store32   loadi32
uint32_t  4 4 store32   loadu32
int64_t   8 8 store64   loadi64
uint64_t  8 8 store64   loadu64
int16_be  2 2 store16be loadi16be
uint16_be 2 2 store16be loadu16be
int24_be  3 1 store24be loadi24be
uint24_be 3 1 store24be loadu24be
int32_be  4 4 store32be loadi32be
uint32_be 4 4 store32be loadu32be
int48_be  6 2 store48be loadi48be
uint48_be 6 2 store48be loadu48be
int64_be  8 8 store64be loadi64be
uint64_be 8 8 store64be loadu64be
int16_le  2 2 store16le loadi16le
uint16_le 2 2 store16le loadu16le
int24_le  3 1 store24le loadi24le
uint24_le 3 1 store24le loadu24le
int32_le  4 4 store32le loadi32le
uint32_le 4 4 store32le loadu32le
int48_le  6 2 store48le loadi48le
uint48_le 6 2 store48le loadu48le
int64_le  8 8 store64le loadi64le
uint64_le 8 8 store64le loadu64le
int16_swap  2 2 store16swap loadi16swap
uint16_swap 2 2 store16swap loadu16swap
int32_swap  4 4 store32swap loadi32swap
uint32_swap 4 4 store32swap loadu32swap
int64_swap  8 8 store64swap loadi64swap
uint64_swap 8 8 store64swap loadu64swap
char      1 1 store8   loadi8
uchar     1 1 store8   loadu8
short     2 2 store16  loadi16
ushort    2 2 store16  loadu16
int 4 4 store32 loadi32
uint 4 4 store32 loadu32
long TypeSpec::SIZEOF_LONG TypeSpec::SIZEOF_LONG store_long load_long
ulong TypeSpec::SIZEOF_LONG TypeSpec::SIZEOF_LONG store_long load_ulong
longlong 8 8 store64 loadi64
ulonglong 8 8 store64 loadu64
float     4 4 storef32  loadf32
double    8 8 storef64  loadf64
float_be  4 4 storef32be loadf32be
double_be 8 8 storef64be  loadf64be
float_le  4 4 storef32le  loadf32le
double_le 8 8 storef64le  loadf64le
float_swap  4 4 storef32swap  loadf32swap
double_swap 8 8 storef64swap  loadf64swap
EOS

File.open(path, "wb") do |f|
  f.puts <<-EOS
#--
# this code is generated by #{File.basename __FILE__}
#++

require_relative "typespec"

module Gogyou
  module Primitives
    class Primitive < ::Struct.new(:name, :bytesize, :bytealign)
      BasicStruct = superclass

      undef :name=, :bytesize=, :bytealign=

      def initialize(name, bytesize, bytealign, aset, aref)
        super(name.intern, bytesize.to_i, bytealign.to_i)
        define_singleton_method(:aset, aset)
        define_singleton_method(:aref, aref)
      end

      def extensible?
        false
      end

      def to_s
        "\\\#<\#{self.class}:\#{name} bytesize=\#{bytesize.inspect}, bytealign=\#{bytealign.inspect}>"
      end

      alias inspect to_s

      def pretty_print(q)
        #name, bytesize, bytealign
        q.group(1, "\\\#<\#{self.class}:\#{name}") do
          q.breakable " "
          q.text "bytesize="
          q.pp bytesize
          q.text ","
          q.breakable " "
          q.text "bytealign="
          q.pp bytealign
        end
        q.text ">"
      end
    end

  EOS

  records = records.split(/\n/)
  records.map! { |r| r.split(/\s+/) }

  records.each do |typename, bytesize, bytealign, aset, aref|
    name = typename.upcase
    f.puts <<-EOS
    #{name.ljust(9)} = Primitive[#{typename.intern.inspect}, #{bytesize}, #{bytealign},
                          ->(buf, offset, num) { buf.#{aset}(offset, num) },
                          ->(buf, offset) { buf.#{aref}(offset) }].freeze
    EOS
  end

  f.puts <<-EOS
  end
end
  EOS
end
